### ISSUE TITLE
Spec Bug

### ISSUE THREAD

**Issue by Stechende** [SA-PP/sa-pp-issues#2]
**Current behavior**
Players can be watched at events.(If you watch the video, you will understand.)

**Expected behavior**
This command should not be used in events.

**Steps to reproduce**
https://youtu.be/GFK66F5Ft4Y

**Context (environment)**
I playing the game, suddenly teleported to the lobby.

**Possible solution**
This command should only be used in the lobby :)

**Comment by insus100** [comment]
It's fixed for next restart thanks for reporting
