### ISSUE TITLE
The server is restarting, CONNECTION REJECTED: Unacceptable NickName

### ISSUE THREAD

**Issue by CZVefty** [SA-PP/sa-pp-issues#3]
**SAMP or Alt:V bug**
SA-MP

**Current behavior**
It will randomly kick me out of the server and writes a message "The server is restarting" "CONNECTION REJECTED: Unacceptable nickname", screenshot attached below.
[CONNECTION SCREENSHOT](https://prnt.sc/ErhndjLp9gyn)

**Expected behavior**
N/A

**Steps to reproduce**
It happens randomly when I play

**Possible solution**
I looked up the internet and I realized that the problem should be on client-side, but I think the problem is on server-side, _because this happens only on SA-PP_. For better comparsion, I attached also screenshots from my speedtest and packetloss on www.google.com.
[SPEEDTEST SCREENSHOT](https://prnt.sc/eH2KRFyNH4Ks)
[PACKETLOSS WWW.GOOGLE.COM SCREENSHOT](https://prnt.sc/4hHRbA3TCj4Z)

And I would like to let you know that my nickname is "Vefty".

**Comment by CZVefty** [comment]
And I would like to let you know that my nickname is "Vefty".

**Comment by insus100** [comment]
What's your average ping?

**Comment by CZVefty** [comment]
Everything is on the screenshots included

**Comment by insus100** [comment]
you're pinging google.com not the server ip

Edit:
Also, have you tried using a VPN?

**Comment by CZVefty** [comment]
Alright, my usual ping is about 30ms

Edit: No, I have not.

**Comment by CZVefty** [comment]
I do not have any VPN purchased, I tried using VPNs, but mostly I had reduced connection speed by half or more, I had more bad experiences than good experiences.

**Comment by insus100** [comment]
But do you have the same connection rejected issue with the VPN?
I checked server logs and couldn't find anything wrong with your connections. I think it's either your ISP having trouble connecting with the server or your firewall.

**Comment by CZVefty** [comment]
I haven't try. Maybe I won't try either, because as I said, I won't pay for VPN. Thanks for reviewing it, I closed this issue.
