### ISSUE TITLE
Leaving as last cop before a pursuit can be started has interesting effects

### ISSUE THREAD

**Issue by Road-Train** [SA-PP/sa-pp-issues#6]
**Current behavior**
[Link to video](https://youtu.be/tqgMVnuvvXE)

**Expected behavior**
Lobby should load normally

**Steps to reproduce**
Have 2 people in the lobby.
Have a round start (aka be teleported into your vehicles)
The COP should leave BEFORE the SUSPECT gets the ability to 'start the pursuit'.
The suspect will end up in the 'lobby' but most of the lobby won't load. The pursuit won't actually start, but the timer will run.

**Context (environment)**
There really isn't much context here.

**Possible solution**
Check in what order the pursuit is started, because whilst the server realizes there's no gamemode running, the timer will count down and it even shows the 'the pursuit has started' message.

**Comment by insus100** [comment]
I reposted your bug report in the forums so Rixas can also respond to it.
https://forum.sa-pp.com/viewtopic.php?t=165
